name: CI/CD for ML Model Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install huggingface_hub

    - name: Login to Hugging Face
      run: huggingface-cli login --token ${{ secrets.HF_TOKEN }}

    - name: Clone Hugging Face Space
      run: |
        git clone https://huggingface.co/spaces/naumansamejaa/sentiment_analysis
        cd sentiment_analysis

    - name: Copy app.py and other files to Hugging Face Space
      run: |
        cp ../app.py .  # Copy the app.py from your project directory to the Hugging Face Space directory
         # Adjust the path if you have additional files or directories

    - name: Deploy model to Hugging Face Space
      run: |
        echo "Deploying model to Hugging Face Space..."
        # Any other deployment steps required by Hugging Face, such as pushing to the space repository
        git add .
        git commit -m "Deploy app"
        git push origin main  # Make sure to push to the correct branch of your Hugging Face space
