name: CI/CD for ML Model Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install huggingface_hub

    - name: Login to Hugging Face
      run: huggingface-cli login --token ${{ secrets.HF_TOKEN }}

    - name: Deploy model to Hugging Face Spaces
      run: |
        # Define space name
        SPACE_NAME="naumansamejaa/sentiment_analysis"  # Space name you created
        # Clone the space repo
        git clone https://huggingface.co/spaces/${SPACE_NAME}
        cd sentiment_analysis
        # Add your model or app files to the cloned space repo
        cp -r ../path_to_your_model_or_app/* .  # Adjust the path to your model/app files
        git add .
        git commit -m "Deploy model update"
        git push
