name: CI/CD for ML Model Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install huggingface_hub

    - name: Login to Hugging Face
      run: echo "${{ secrets.HF_TOKEN }}" | huggingface-cli login --token

    - name: Deploy model to Hugging Face Spaces
      run: |
        # Add your commands here to deploy the model or push it to Hugging Face
        echo "Deplo
