name: CI/CD for ML Model Deployment

on:
  push:
    branches:
      - master  # or the default branch you use

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Hugging Face Hub CLI
        run: |
          pip install huggingface_hub

      - name: Log in to Hugging Face
        run: |
          echo "${{ secrets.HF_TOKEN }}" | huggingface-cli login

      - name: Deploy Model to Hugging Face
        run: |
          # Add the command to deploy your model or push the model file
          huggingface-cli repo create your-model-name --private
          git lfs install
          git add .
          git commit -m "Initial commit"
          git push
