name: CI/CD for ML Model Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install huggingface_hub

    - name: Login to Hugging Face
      run: huggingface-cli login --token ${{ secrets.HF_TOKEN }}

    - name: Deploy model to Hugging Face Spaces
      run: |
        echo "Deploying model to Hugging Face Spaces..."
        huggingface-cli repo create my-space --type space --private
        cd your-model-directory  # change this to where your model files are located
        git init
        git remote add origin https://huggingface.co/spaces/your-username/my-space
        git add .
        git commit -m "Deploy model"
        git push -u origin master
