name: CI/CD for ML Model Deployment

on:
  push:
    branches:
      - master  # Change to main if that's the branch you're using

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install huggingface_hub

    - name: Login to Hugging Face
      run: huggingface-cli login --token ${{ secrets.HF_TOKEN }}

    - name: Copy app.py and other files to Hugging Face Space
      run: |
        mkdir -p space_dir  # Create directory for Hugging Face Space
        cp ../../app.py space_dir/  # Correct path to app.py
        # Add any other necessary files to the space directory:
        cp -r ../../your_model_files/* space_dir/  # Replace with actual model file path

    - name: Push files to Hugging Face Space
      run: |
        cd space_dir
        git init
        git remote add origin https://huggingface.co/spaces/naumansamejaa/sentiment_analysis
        git add .
        git commit -m "Deploying model to Hugging Face Space"
        git push -u origin master  # Change to main if that's the branch you're using
