name: CI/CD for ML Model Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install huggingface_hub

    - name: Login to Hugging Face
      run: huggingface-cli login --token ${{ secrets.HF_TOKEN }}

    - name: Deploy app to Hugging Face Space
      run: |
        # Clone the space directory
        git clone https://huggingface.co/spaces/naumansamejaa/sentiment_analysis
        cd sentiment_analysis

        # Copy the app.py from your project directory to the Hugging Face Space directory
        cp ../app.py .

        # Push changes to Hugging Face Space
        git add app.py
        git commit -m "Deploying app.py to Hugging Face Space"
        git push
